In [ ]:
#2nd september practise

In [5]:
import numpy as np
marks = [10,20,30,40,50]
marks2 = np.array(marks)
print(marks2)

[10 20 30 40 50]


In [13]:
a=np.array([10,20,30,40,50])
b=np.array([20,30,40,50,60])
print(a+b)
print(b-a)
print(a*b)
print(b/a)

[ 30  50  70  90 110]
[10 10 10 10 10]
[ 200  600 1200 2000 3000]
[2.         1.5        1.33333333 1.25       1.2       ]


In [18]:
#marks=[10,20,30,40,50]
#print(marks+5)
#we will get error from this type of operation
marks=np.array([10,20,30,40,50])
new_marks=marks+5
print(new_marks)
print(type(marks))

[15 25 35 45 55]
<class 'numpy.ndarray'>


In [22]:
#2D array
marks = np.array([[1,2,3],[8,3,0],[1,2,3]])
print(marks+2)

[[ 3  4  5]
 [10  5  2]
 [ 3  4  5]]


In [23]:
marks = np.array([10,20,30,40,50])
print(np.sum(marks))
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))
print(np.argmax(marks))
print(np.argmin(marks))
print(np.sqrt(marks))
print(marks**2)

150
30.0
50
10
4
0
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[ 100  400  900 1600 2500]


In [26]:
marks = np.array([[1,2,0],[4,2,2],[1,5,3]])
print(np.sum(marks))
print(np.sum(marks,axis=0))#addition of column
print(np.sum(marks,axis=1))#addition of row 

20
[6 9 5]
[3 8 9]


In [34]:
#slicing of array
marks = np.array([10,20,30,40,50])
print(marks[0:4])
print(marks[1:3])
print(marks[0:])
print(marks[:2])

[10 20 30 40]
[20 30]
[10 20 30 40 50]
[10 20]


In [29]:
marks=np.array([10,20,30,40,50,60,70])
print(marks>50)
print(marks<50)
print(marks==30)

[False False False False False  True  True]
[ True  True  True  True False False False]
[False False  True False False False False]


In [44]:
marks=np.array([10,20,30,40,50,60,70,80])
print(marks[-3:])
print(marks[:-4])
print(marks[-4:-1])
print(marks[-1:-4])
#slicing with addition of step
print(marks[0:4:2])
print(marks[0:5:2])
print(marks[-6:-1:2])

[60 70 80]
[10 20 30 40]
[50 60 70]
[]
[10 30]
[10 30 50]
[30 50 70]
