In [ ]:
#Array Arithmetic
"""
Write a Python program using NumPy to create two arrays:
a = np.array([10, 20, 30])
b = np.array([2, 4, 5])
Perform and display:
● Addition: a + b
● Subtraction: a - b
● Multiplication: a * b
● Division: a / b
"""
import numpy as np

a = np.array([10,20,30])
b = np.array([2,4,5])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[12 24 35]
[ 8 16 25]
[ 20  80 150]
[5. 5. 6.]


In [ ]:
#Checking Data Type
"""
Create a NumPy array:
arr = np.array([10, 20, 30, 40])
Write Python code to display the data type of the variable arr.
"""
import numpy as np

arr = np.array([10,20,30,40])
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
#Creating a 2D Array
"""
Create the following 2D NumPy array and display it:
10  20  30
40  50  60
70  80  90
"""
import numpy as np
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
#NumPy Mathematical Functions – Find the Correct Function
"""
Consider:
import numpy as np
marks = np.array([45, 72, 89, 56, 95, 68])
Write NumPy code to display:
1. The average of the marks.
2. The position (index) of the highest mark.
3. The smallest mark.
Use appropriate NumPy functions.
"""
import numpy as np

marks = np.array([45, 72, 89, 56, 95, 68])
average = marks.sum()/len(marks)
highest_index = np.argmax(marks)
min_value= np.min(marks)
print("Average:",average)
print("Index of maximum value:",highest_index)
print("Minimum value:",min_value)

Average: 70.83333333333333
Index of maximum value: 4
Minimum value: 45


In [ ]:
#Comparing Array Elements
"""
Consider:
arr = np.array([10, 25, 30, 45, 50])
Write NumPy statements to display:
1. Elements greater than 30
2. Elements less than 30
3. Elements equal to 30
"""
import numpy as np


arr = np.array([10, 25, 30, 45, 50])

print("Elements greater than 30:",arr[arr>30])
print("Elements less than 30:",arr[arr<30])
print("Elements equal to 30:",arr[arr==30])

Elements greater than 30: [45 50]
Elements less than 30: [10 25]
Elements equal to 30: [30]


In [1]:
#Processing a 2D Array Using sum()
"""
Consider:
arr = np.array([
[10, 20, 30],
[40, 50, 60],
[70, 80, 90]
])
Write NumPy code to display:
1. The sum of all elements.
2. The sum of each column using axis=0.
3. The sum of each row using axis=1.
"""
import numpy as np

arr = np.array([
[10, 20, 30],
[40, 50, 60],
[70, 80, 90]
])

print("Sum of all elements:",np.sum(arr))
print("Sum of each column (axis=0):", np.sum(arr, axis=0))
print("Sum of each row (axis=1):", np.sum(arr, axis=1))

Sum of all elements: 450
Sum of each column (axis=0): [120 150 180]
Sum of each row (axis=1): [ 60 150 240]


In [2]:
#Positive Index Slicing"
"""
Consider:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
Write slicing statements to display:
1. Elements from index 2 to the end.
2. Elements from the beginning up to index 4
3. Elements from index 1 to index 5.
"""
import numpy as np

arr = np.array([10,20,30,40,50,60,70])
print("Index 2 to end:", arr[2:])
print("Beginning up to index 4:", arr[:4])
print("Index 1 to index 5:", arr[1:5])

Index 2 to end: [30 40 50 60 70]
Beginning up to index 4: [10 20 30 40]
Index 1 to index 5: [20 30 40 50]


In [3]:
#Negative Index Slicing
"""
Consider:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
Using negative indexing, write slicing statements to display:
1. The last 3 elements.
2. All elements except the last 2 elements.
3. The elements from the 5th-last position up to the 2nd-last position.
"""
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70])

print("Last 3 elements:", arr[-3:])
print("All except last 2 elements:", arr[:-2])
print("5th-last to 2nd-last position:", arr[-5:-1])

Last 3 elements: [50 60 70]
All except last 2 elements: [10 20 30 40 50]
5th-last to 2nd-last position: [30 40 50 60]


In [4]:
#Slicing with Step
"""
Consider:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
Write NumPy slicing statements to:
1. Display every second element starting from the first element.
2. Display every second element starting from the second element.
3. Reverse the complete array using slicing.
"""
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print("Every 2nd element from 1st element:", arr[::2])
print("Every 2nd element from 2nd element:", arr[1::2])
print("Reversed array:", arr[::-1])

Every 2nd element from 1st element: [10 30 50 70]
Every 2nd element from 2nd element: [20 40 60 80]
Reversed array: [80 70 60 50 40 30 20 10]


In [5]:
#Mixed Operations
"""
Consider:
arr = np.array([15, 40, 25, 80, 35, 60, 10])
Write NumPy code to:
1. Find the maximum value.
2. Find the index of the minimum value.
3. Display only the values greater than 30.
4. Display the last three elements using negative indexing.
"""
import numpy as np

arr = np.array([15, 40, 25, 80, 35, 60, 10])

print("Maximum value:", np.max(arr))
print("Index of minimum value:", np.argmin(arr))
print("Values greater than 30:", arr[arr > 30])
print("Last three elements:", arr[-3:])

Maximum value: 80
Index of minimum value: 6
Values greater than 30: [40 80 35 60]
Last three elements: [35 60 10]
