In [31]:

import numpy as np

arr1 = np.array([[1,2,3,4],[2,3,4,5]])
arr2 = np.array([[1,2,3,4],[2,3,4,5]])
arr3= np.array([[[1,2,3,4],[2,3,4,5]],[[1,2,3,4],[2,3,4,5]]])
arr4= np.array([[[1,2,3,4],[2,3,4,5]],[[1,2,3,4],[2,3,4,5]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr3.ndim)
print("Addition of two 2D arrays")
print(arr1+arr2)
print()
print("Subtraction of two 2D array")
print(arr1-arr2)
print()
print("Multiplication of two 2D arrays")
print(arr1*arr2)
print()
print("Divison of two 2D arrays")
print(arr1/arr2)
print()
print("Modulus of two 2D arrays")
print(arr1%arr2)
print()
print("Addition of two 3D arrays")
print(arr3+arr4)
print()
print("Subtraction of two 3d arrays")
print(arr3-arr4)
print()


[1 2 3 4]
<class 'numpy.ndarray'>
1
3
Addition of two 2D arrays
[[ 2  4  6  8]
 [ 4  6  8 10]]

Subtraction of two 2D array
[[0 0 0 0]
 [0 0 0 0]]

Multiplication of two 2D arrays
[[ 1  4  9 16]
 [ 4  9 16 25]]

Divison of two 2D arrays
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Modulus of two 2D arrays
[[0 0 0 0]
 [0 0 0 0]]

Addition of two 3D arrays
[[[ 2  4  6  8]
  [ 4  6  8 10]]

 [[ 2  4  6  8]
  [ 4  6  8 10]]]

Subtraction of two 3d arrays
[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]

